### ISSUE TITLE
Is this package available on PyPI?

### ISSUE THREAD

**Issue by dougthor42** [brandontksmith/adp-connection-python#2]
Is this package available on PyPI? Or is it only installable via github download?

**Comment by brandontksmith** [comment]
It is currently only installed via github download.

**Comment by dougthor42** [comment]
Good to know, thanks!

For anyone finding this, you can still use pip:

```
pip install git+git://github.com/brandontksmith/adp-connection-python.git@master#egg=adp-connection
```

See the [pip docs for VCS support](https://pip.pypa.io/en/stable/reference/pip_install/#git).
