### ISSUE TITLE
More ADP Questions

### ISSUE THREAD

**Issue by TannerHolle** [brandontksmith/adp-connection-python#3]
Brandon,

I reached out to you via github a while ago regarding a few issues I had working with ADP. I am trying to pull data through the payroll output API but the data that is coming back is much less than what the documentation is showing should be. Do you know what might be causing that and how to get all the data to come back? Sorry for asking you but you helped a ton last time.

Tanner

**Comment by brandontksmith** [comment]
> Brandon,
> 
> I reached out to you via github a while ago regarding a few issues I had working with ADP. I am trying to pull data through the payroll output API but the data that is coming back is much less than what the documentation is showing should be. Do you know what might be causing that and how to get all the data to come back? Sorry for asking you but you helped a ton last time.
> 
> Tanner

Which ADP Product i.e. RUN, Workforce Now? If I recall, I did not receive all of the data in the sample response. It varies based on the ADP Product.
